import { FadeIn } from "@/components/home/FadeIn";

const Disclaimer = () => (
  <div className="py-12 px-4">
    <div className="max-w-2xl mx-auto">
      <FadeIn>
        <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tighter mb-6">Disclaimer</h1>
      </FadeIn>
      <FadeIn delay={100}>
        <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
          <p>Last updated: February 2026</p>

          <h2 className="text-lg font-bold text-foreground">General Information</h2>
          <p>
            The information and tools provided on WakeupAI (wakeupai.in) are for general
            informational and creative purposes only. While we strive to provide useful and accurate
            cinematic prompt generation, we make no representations or warranties about the
            completeness, accuracy, or reliability of the generated content.
          </p>

          <h2 className="text-lg font-bold text-foreground">AI-Generated Content</h2>
          <p>
            The prompts generated by WakeupAI are created using artificial intelligence. Results may
            vary depending on the AI video tool you use and its current capabilities. We do not
            guarantee specific outcomes from any AI video generation platform.
          </p>

          <h2 className="text-lg font-bold text-foreground">Third-Party Tools</h2>
          <p>
            WakeupAI is not affiliated with, endorsed by, or connected to any AI video generation
            platform including but not limited to Runway, Pika Labs, OpenAI Sora, Kling AI, or Luma
            Dream Machine. Mentions of these tools are for informational purposes only.
          </p>

          <h2 className="text-lg font-bold text-foreground">No Professional Advice</h2>
          <p>
            The content on this website, including blog posts and generated prompts, does not
            constitute professional filmmaking, legal, or business advice. Users should exercise
            their own judgment when using generated content for commercial purposes.
          </p>

          <h2 className="text-lg font-bold text-foreground">External Links</h2>
          <p>
            This website may contain links to external websites. We are not responsible for the
            content, privacy practices, or availability of these third-party sites.
          </p>

          <h2 className="text-lg font-bold text-foreground">Limitation of Liability</h2>
          <p>
            Under no circumstances shall WakeupAI be held liable for any damages arising from the
            use or inability to use the Service, including but not limited to direct, indirect,
            incidental, or consequential damages.
          </p>

          <h2 className="text-lg font-bold text-foreground">Contact</h2>
          <p>
            If you have questions about this Disclaimer, contact us at{" "}
            <a href="mailto:dhruvxrana@gmail.com" className="text-foreground underline underline-offset-4">
              dhruvxrana@gmail.com
            </a>
            .
          </p>
        </div>
      </FadeIn>
    </div>
  </div>
);

export default Disclaimer;
