import { FadeIn } from "@/components/home/FadeIn";

const Terms = () => (
  <div className="py-12 px-4">
    <div className="max-w-2xl mx-auto">
      <FadeIn>
        <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tighter mb-6">Terms of Service</h1>
      </FadeIn>
      <FadeIn delay={100}>
        <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
          <p>Last updated: February 2026</p>
          <p>
            By using WakeupAI ("the Service"), you agree to these Terms of Service. Please read them
            carefully before using the website.
          </p>

          <h2 className="text-lg font-bold text-foreground">Use of Service</h2>
          <p>
            WakeupAI provides an AI-powered cinematic scene prompt generator. The Service is provided
            free of charge for personal and commercial use.
          </p>
          <p>
            You may use the prompts generated by WakeupAI for any lawful purpose, including commercial
            projects, content creation, and client work.
          </p>

          <h2 className="text-lg font-bold text-foreground">Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the Service for any illegal or unauthorized purpose</li>
            <li>Attempt to overwhelm or abuse the Service through automated requests</li>
            <li>Reverse engineer, decompile, or attempt to extract the source code</li>
            <li>Generate content that promotes violence, hate speech, or illegal activities</li>
          </ul>

          <h2 className="text-lg font-bold text-foreground">Intellectual Property</h2>
          <p>
            The prompts generated by the Service are provided for your use. WakeupAI does not claim
            ownership of the prompts you generate. The WakeupAI name, logo, and website design are
            our intellectual property.
          </p>

          <h2 className="text-lg font-bold text-foreground">Disclaimer of Warranties</h2>
          <p>
            The Service is provided "as is" without warranties of any kind. We do not guarantee that
            the Service will be uninterrupted, error-free, or that the generated prompts will produce
            specific results with any particular AI video tool.
          </p>

          <h2 className="text-lg font-bold text-foreground">Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, WakeupAI shall not be liable for any indirect,
            incidental, special, or consequential damages arising from your use of the Service.
          </p>

          <h2 className="text-lg font-bold text-foreground">Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. Continued use of the Service
            constitutes acceptance of the modified Terms.
          </p>

          <h2 className="text-lg font-bold text-foreground">Contact</h2>
          <p>
            For questions about these Terms, contact us at{" "}
            <a href="mailto:hello@wakeupai.in" className="text-foreground underline underline-offset-4">
              hello@wakeupai.in
            </a>
            .
          </p>
        </div>
      </FadeIn>
    </div>
  </div>
);

export default Terms;
