import { FadeIn } from "./FadeIn";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    q: "What is an AI video scene generator?",
    a: "An AI video scene generator transforms simple scene descriptions into detailed, professional cinematic prompts. These prompts can be used with AI video tools like Runway, Pika, Sora, and others to create high-quality video content.",
  },
  {
    q: "Is WakeupAI free to use?",
    a: "Yes, WakeupAI is completely free. No login, no subscription, no credit card required. Just describe your scene and generate your cinematic prompt instantly.",
  },
  {
    q: "Which AI video tools does this work with?",
    a: "The prompts generated by WakeupAI work with all major AI video generation tools including Runway Gen-3, Pika Labs, Kling AI, Luma Dream Machine, OpenAI Sora, and more.",
  },
  {
    q: "Do I need filmmaking knowledge?",
    a: "Not at all. WakeupAI is designed for creators without technical filmmaking knowledge. Simply describe your scene in plain English and the AI will add professional cinematic elements like camera angles, lighting, and mood direction.",
  },
  {
    q: "How accurate are the generated prompts?",
    a: "Our AI uses professional filmmaking language and cinematic vocabulary to create prompts that maximize the quality of AI-generated videos. The storyboard breakdown helps you visualize the complete scene before generating.",
  },
  {
    q: "Can I use the prompts commercially?",
    a: "Yes. All prompts generated by WakeupAI are yours to use for any purpose, including commercial projects, YouTube videos, social media content, and client work.",
  },
];

export const FAQSection = () => (
  <section id="faq" className="py-20 px-4 bg-secondary/50">
    <div className="max-w-3xl mx-auto">
      <FadeIn>
        <h2 className="text-2xl sm:text-3xl font-extrabold tracking-tighter text-center mb-12">
          Frequently Asked Questions
        </h2>
      </FadeIn>
      <FadeIn delay={100}>
        <Accordion type="single" collapsible className="space-y-2">
          {faqs.map((faq, i) => (
            <AccordionItem
              key={i}
              value={`faq-${i}`}
              className="border rounded-xl px-4 bg-card"
            >
              <AccordionTrigger className="text-left font-semibold text-sm hover:no-underline">
                {faq.q}
              </AccordionTrigger>
              <AccordionContent className="text-sm text-muted-foreground leading-relaxed">
                {faq.a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </FadeIn>
    </div>
  </section>
);
